[tool.poetry]
name = "game-solvers"
version = "0.1.0"
description = "CLI application for solving puzzle games"
authors = ["Matt Mulligan <matt@mattmulligan.net>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.12"
pyapp = "~= 4.15"
rich = "~= 13.7"

[tool.poetry.group.dev.dependencies]
pytest = "~= 8.2"
pytest-cov = "~= 5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
