name: 'PR Workflow: Master'

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
      
jobs:
  pre-checks-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (3.11)
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '~=3.11.0'

      - name: Setup Python (3.12)
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '~=3.12.0'

      - name: Install Poetry
        run: pip install poetry

      - name: Setup Poetry Env
        run: poetry install

      - name: Run Ruff Linter Checks
        run: poetry run ruff check

      - name: Run Ruff Formatter Checks
        run: poetry run ruff format

      - name: Run MyPy Checks
        run: poetry run mypy ./src

      - name: Run Unit Tests
        run: poetry run nox -s unit-tests
