name: 'Push: Feature Branch'

on:
  push:
    branches:
      - 'feature/**'
      
jobs:
  push-checks-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (3.11)
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '~=3.11.0'

      - name: Setup Python (3.12)
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '~=3.12.0'

      - name: Install Poetry
        run: pip install poetry

      - name: Setup Poetry Env
        run: poetry install

      - name: Run Ruff Linter Checks
        run: poetry run ruff check

      - name: Run Ruff Formatter Checks
        run: poetry run ruff formatter

      - name: Run MyPy Checks
        run: poetry run mypy

      - name: Run Unit Tests
        run: poetry run nox -s unit-tests
